test import rsrcs

diff --git a/.github/workflows/deploy-apim.yml b/.github/workflows/deploy-apim.yml
--- a/.github/workflows/deploy-apim.yml
+++ b/.github/workflows/deploy-apim.yml
@@ -63,6 +63,12 @@ jobs:
           cd environments/${{ env.ENVIRONMENT }}
           RESOURCE_GROUP="${{ secrets.AZURE_RESOURCE_GROUP }}"
           SUBSCRIPTION_ID="${{ secrets.AZURE_SUBSCRIPTION_ID }}"
+
+          if [ -z "$RESOURCE_GROUP" ]; then
+            echo "❌ ERROR: AZURE_RESOURCE_GROUP is not set!"
+            exit 1
+          fi
+          
           terraform import  -var="environment=${{ env.ENVIRONMENT }} " -var="subscription_id=${{  env.SUBSCRIPTION_ID }} " -var="azurerm_resource_group=${{ env.AZURE_RESOURCE_GROUP }}" azurerm_resource_group.rg "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP"  || echo "✅ Resource already imported"
           terraform import  -var="environment=${{ env.ENVIRONMENT }} " -var="subscription_id=${{  env.SUBSCRIPTION_ID }} " -var="azurerm_resource_group=${{ env.AZURE_RESOURCE_GROUP }}" azurerm_api_management.apim "/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.ApiManagement/service/apim-${{ env.ENVIRONMENT }}"|| echo "✅ APIM already imported"
 
